### PR TITLE
Updated the new X logo in footer section

### PR DESCRIPTION
**Pull request by Murdock9803**
Fixes issue #99 

### Changes done
- [x] Deleted the old twitter logo
- [x] Added the new X logo (SVG file)
- [x] kept consistency in the name of logo file (format)
- [x] Updated logo in `footer.html`

### CODE REVIEW

**Comment by Murdock9803** [comment]
@kgodey  Please review the PR. Thanks

**Comment by ghislaineguerin** [comment]
Thanks, looks good!

**Comment by Murdock9803** [comment]
@ghislaineguerin @seancolsen wishing you a very Happy New Year 🎊 
Can you guide me about the project ideas that Mathesar Foundation is looking forward for GSoC'24 ? I want to work with the org in and after google summer of code. My tech stack is mainly based on (but not limited to) JavaScript.

**Comment by seancolsen** [comment]
@Murdock9803 I'm sorry but Mathesar will [not be participating in GSoC 2024](https://github.com/mathesar-foundation/mathesar/issues/3381)

**Pull request merged**
