### PR TITLE
Add blog post for GitHub Open Source Fridays talks

### PR DESCRIPTION
**Pull request by seancolsen**
Screenshot_20240319_164919

Screenshot_20240319_165001

### CODE REVIEW

**Comment by seancolsen** [comment]
This is a start but there's an issue with the blog system that I think we ought to fix before publishing this...

Tags are messed up. It looks like every post gets the combinations of tags that all posts have.

@ghislaineguerin do you think you could fix this? I'm assigning you to this PR so that you can look into it.

@kgodey I'm assigning you so that you can review from a content perspective.

**Comment by kgodey** [comment]
@seancolsen Could you switch from third person to first person, since the post is authored by you? It would also be nice to add a paragraph with some details about your personal experience with the stream. 

Here are some articles about people's experience at conferences, for examples of tone, it doesn't have to be this long though:
https://julianaalmeida.hashnode.dev/babys-first-pgconf
https://andyatkinson.com/blog/2023/10/10/pgconf-nyc-2023

**Comment by seancolsen** [comment]
@kgodey ready for re-review.

**Comment by kgodey** [comment]
@seancolsen Looks good, I made some minor updates. 

@ghislaineguerin Can you fix the tags and also maybe make a custom featured image that matches the blog image ratio better? It doesn't have to be a variation of the existing featured image, it can be our own thing.

**Comment by seancolsen** [comment]
> make a custom featured image that matches the blog image ratio better?

Instead of this, I'd like to reiterate this previous [suggestion](https://github.com/mathesar-foundation/mathesar-website/pull/89#issuecomment-1942118563) of mine:

> Accommodate a wide range of aspect ratios without cropping. Wide images would be scaled down so that their height is rather short. Tall images would be scaled to a max height and then pillarboxed with empty space on the left and right.

I've been biting my tongue on this, but I'm piping up again since the topic has resurfaced. I contend that if we think of this problem in terms of "the blog image ratio", we're going to be fighting an uphill battle. Rather, it would be better to put our effort towards CSS that gracefully accommodates a range of aspect ratios.

Our current image CSS is an improvement over what I saw originally, but it still has problems like this:



Yikes! In this case the cropping makes it look like we've just released Mathesar 1.5.

Additionally, I find the blurred background filter to be pretty jarring aesthetically. For example:

image

I wouldn't imagine it to be too difficult to tweak the CSS so that the post summaries look good with any image aspect ratio and any viewport width. If we took that approach, then we could avoid the extra time to create custom images for this post and for future posts.

**Comment by kgodey** [comment]
@seancolsen Sure, that approach is fine with me as well, and does seem better for the longer term. Could you help @ghislaineguerin figure out the CSS if needed?

**Comment by seancolsen** [comment]
> Could you help @ghislaineguerin figure out the CSS if needed?

Absolutely. Ghislaine, let me know if you'd like help. We could even hop on a call and do this via pairing.

**Comment by ghislaineguerin** [comment]
Thanks @seancolsen . I have fixed the tags issue. I will now fix the featured image. I will try and let you know if I need help.

**Comment by ghislaineguerin** [comment]
@seancolsen Can you please review the featured image fix? Thanks!

**Comment by kgodey** [comment]
I'd like to get this merged since the tag fixes are blocking the funding announcement post, but I think that the image for 0.1.4 is way too tall. @ghislaineguerin Can you make a custom image for 0.1.4 using the screenshot that we have as the featured image and replace the featured image with that one?

**Comment by seancolsen** [comment]
(Commenting since GitHub won't let me review my own PR...)

I **approve** the changes ✅

As all the content and code stands in this PR, I think the overall behavior is satisfactory, especially given our other priorities with the beta.

But I still think that at some point it would be nice to adjust the CSS more. I peeked into this PR last week briefly before I had time to submit a full review, and I noticed the same issue that Kriti pointed out — one image was too tall. You've addressed that by changing the image. That's fine for now, but I would be inclined to set a `max-height` on the image instead. This is not a huge deal, but something to consider if we run into this challenge again.

**Comment by seancolsen** [comment]
@kgodey I'll leave it to you to merge this. We're good-to-go from my end.

**Pull request merged**
