### PR TITLE
Update Team Page

### PR DESCRIPTION
**Pull request by ghislaineguerin**
Context: https://3.basecamp.com/5718119/buckets/35366254/todos/6806795586
- Added sections for Board Members, Advisory Board and Other Foundation Staff
- Terminology updates

### CODE REVIEW

**Comment by kgodey** [comment]
@ghislaineguerin Feedback:
- The maintainers section should be above the board / advisory board section.
- Let's actually remove the "advisory board" section, we only have one person to add for now, and I'd like to talk to some other people about being advisors and we can add this section once we have a few people to list.
- I think the "other staff" should have the same prominence as maintainers – same size, bio, etc. and it should be in the same "box" as the maintainers, it shouldn't be with the board
- Can we add something a bit more visually interesting to the "Mathesar is maintained by the Mathesar Foundation, a 501(c)(3) nonprofit based out of the US." section? I liked how we had the CCI logo, although we don't have a logo for the foundation, can we do something else? or just make a quick logo that says Mathesar Foundation using our elephant? or just use the elephant by itself?

I'll work on copy once the design has been finalized.

**Comment by ghislaineguerin** [comment]
@kgodey 
Thanks for the feedback. The 3 latest blog posts were included in the homepage at the bottom. Maybe you've missed them so we might need to make them more prominent.

**Comment by kgodey** [comment]
@ghislaineguerin there are no new changes pushed here, what am I supposed to be reviewing?

**Comment by ghislaineguerin** [comment]
@kgodey I've pushed updates for all your points in: https://github.com/mathesar-foundation/mathesar-website/pull/101#issuecomment-1915739823

**Comment by kgodey** [comment]
@ghislaineguerin Thanks, not sure why it didn't show up for me earlier.

This looks mostly good. Three things:
(1) Can we put the board members below our contributors?
(2) The "other staff" section looks a bit awkward. Can we just combine all staff into one section and just call it "Our staff" instead of "maintainers"? We show everyone's titles, we can make it clear who is a maintainer and who's not there.
(3) Is the foundation logo a placeholder? The proportions look pretty weird
Screenshot 2024-02-08 at 5 21 57 PM

**Comment by kgodey** [comment]
@ghislaineguerin I pushed some changes, a couple more things.

(1) Can you check the alignment of the board photos? They seem to all be aligned totally differently.

Screen Shot 2024-02-09 at 2 57 12 PM

(2) I made some changes to the "Mathesar Foundation" text, and the logo alignment looks different now. I still think the original design is much better, can we go back to something closer to that?

### Original design
Screen Shot 2024-02-09 at 3 01 06 PM

### Design in this PR

Screen Shot 2024-02-09 at 2 59 45 PM

Issues with new design:

(a) The really small separate section for just one header and a paragraph looks really weird. Can we integrate into the sand colored section like we have on the currently deployed version of the website?

(b) I think the logo makes more sense on the right than the left, people read from left to right.

(c) The word "Mathesar" is repeated too many times, since it's in the logo, it's twice in the text, once in the header. I think we need to adjust the logo so it's not so similar to the text. The CCI logo worked there because it used a completely different font etc. I can work on adjusting the text to compensate once we adjust the logo, or you can feel free to make changes to the text yourself too.

**Comment by kgodey** [comment]
This is not yet ready for review, right? I saw a Basecamp task but it's gone now.

**Comment by kgodey** [comment]
@ghislaineguerin Thanks, this looks great. I agree the logo and copy around it could be improved, but I think this is good enough to merge now, we can improve later when we do a larger website overhaul. For some reason making the color black and moving the image to the right makes the "Mathesar" repetition not so obvious.

I have also updated everyone's names and bios with the final data. The alignment on Sam and Ian's titles looks a bit odd, could we constrain the max width so that the second line is not so narrow compared to the first line?

Screenshot 2024-02-21 at 10 08 36 PM

Once you fix this, you can merge, no further review needed. Thanks for your work on this!

**Comment by kgodey** [comment]
@ghislaineguerin Thanks for merging! One quick thing - I saw you cropped Adam's image to a square, can you adjust the crop so that Adam's head is not cut off at the top?

**Pull request merged**
