### PR TITLE
Add Blog Page

### LINKED ISSUE #88: Add a Blog Page
### Problem
As part of our ongoing efforts to improve communication and engagement with our users (see [Gather User Feedback](https://wiki.mathesar.org/en/projects/gather-user-feedback)), we need a dedicated space on our website where we can share updates, survey results, changelog info, and other relevant content.

### Proposed Solution
We will add a blog page to the Mathesar website and establish a process for creating and publishing blog posts. The blog page will include blog post listings with titles, brief excerpts, and publication dates, as well as individual post pages with full content. 

Even though at the moment we may not be able to produce highly sophisticated content, having this space will provide us with an opportunity to reach out to visitors and share important project updates.

### Reference
Here are a couple of examples of how other projects are using their blogs:

[NetBox Blog](https://netbox.dev/blog/) - They use their blog for posting surveys and changelog information. The content is concise and focused.
[Pulsar Edit Blog](https://pulsar-edit.dev/blog/) - They post detailed analysis of survey results, giving their users insights into the decisions being made based on the feedback received.

- [ ] Design the blog page layout
- [ ] Implement the blog page into the current Mathesar website

### PR DESCRIPTION
**Pull request by ghislaineguerin**
Fixes #88

### CODE REVIEW

**Comment by kgodey** [comment]
@ghislaineguerin Nice work. Feedback:

- Homepage
    - We need someplace on the home page to show links to latest blog post(s). It could just be a banner, or a card with an image and the first few lines of the text. I think it's important to show that we're regularly doing new things right on the homepage.
- Blog home
    - It doesn't seem like clicking on the tags does anything
    - We should have images for each blog post for social media sharing, etc. We probably want to show one image on this page too, for each entry.
- Blog entry page
    - The "posted by author name" is showing both at the beginning and end of the blog post. I don't think we need it at the end.
    - It doesn't seem like clicking on the tags does anything
    - We need a featured image for each entry.
    - Do we need the navigation to other blog posts? If we do have it, it should be at the bottom to be less distracting from the main content
        - examples: https://baserow.io/blog/find-remove-duplicates shows the most recent posts at the bottom, https://creativecommons.org/2024/01/24/what-did-creative-commons-do-for-open-culture-in-2023/ shows "related" posts at the bottom
- I assume we need designs for blog entry lists if you click on an author (all posts published by that author, e.g. https://creativecommons.org/person/annacreativecommons-org/) and all posts with that tag.

**Comment by ghislaineguerin** [comment]
@kgodey 
Thanks for the feedback. The 3 latest blog posts were included in the homepage at the bottom. Maybe you've missed them so we might need to make them more prominent.

**Comment by kgodey** [comment]
@ghislaineguerin I did not scroll to the bottom, I don't think we can expect users to do that since the page is so long.

**Comment by ghislaineguerin** [comment]
@kgodey I will move it higher up the page.

**Comment by kgodey** [comment]
@ghislaineguerin Thanks for making the changes, feedback:

### Homepage

(1) The blog section on the homepage doesn't make sense, it breaks the flow of the page. People are supposed to read our copy from the top to the bottom, adding a section in the middle that links out to other pages is really confusing.

(2) The blog section is also below the fold. We want users to see new blog posts when they come to the website. If someone's already visited the website before and read the copy, they are not going to scroll below the fold.

(3) I don't think we need the blog post to be in a card layout and show pictures and all that (on the homepage), it's too distracting / busy. 

I think we should be aiming for only showing the date + title of the latest blog post with some sort of "read more" link, it should be above the fold. Something more like the banner for the survey (but obviously not competing with the survey banner)

### Blog home

(1) This looks far too empty on my 13" Macbook screen – can we make the content wider and use less whitespace?
Screenshot 2024-02-07 at 01-04-01 Blog - Mathesar

(2) Either the whole card should be clickable or we should have some sort of "read full article" type link after the excerpt. It's confusing that only the title is clickable to navigate to the blog entry.

Featured image looks good.

### Author page

Screenshot 2024-02-07 at 01-06-34 Author Kriti Godey

(1) Photo and bio should be at the bottom, it's probably not the most relevant information if someone's looking for blog posts.

(2) Photo and bio are taking up WAY too much room, they should be much more compact. I think photo and bio should next to each other, not stacked.

(3) Same page emptiness issue as blog homepage

(4) The page title doesn't make sense without context, the title should still say "Mathesar blog" and we should have the "Posts by [author name]" text in the same place that "Latest news and updates from the Mathesar team." is on the main blog page.

(5) We don't need website links for authors.

### Tag page

Screenshot 2024-02-07 at 01-11-19 Tag announcement

(1) Same page emptiness issue

(2) Same issue with page title as author page

(3) Please add quotes around the tag name in the text i.e. Posts tagged "tag name"

### Blog entry page
Screenshot 2024-02-07 at 01-14-40 Test

(1) I think we need to do some work on the text spacing to make it more readable and "blog" like, there's far too much line height. Please let me know if you need more detail.

(2) Can we have a page background similar to the rest of the blog pages, where the entry is white and the background is sand?

(3) The "Our blog" header at the bottom is confusing, it should say maybe "Recent blog posts" or something like that. I assume we will show the most recent blog posts that are not the same blog post as the current page, let me know if that algorithm is inaccurate.

(4) The "Our blog" section has too much whitespace too.

The content width in this page looks better than the earlier pages.

**Comment by seancolsen** [comment]
I'm poking my head into this PR because @kgodey [assigned](https://3.basecamp.com/5718119/buckets/35537802/todos/6950569197) me to write a blog post for the 0.1.4 release.

One piece of general feedback on the blog itself though...

- How can I access an RSS feed for the blog? I would suggest making an RSS feed a requirement before we publish any sort of blog.

**Comment by seancolsen** [comment]
@kgodey In 80f8be3adea7038181e0601e3b3bb35ab7d37c95 I added a blog post for the 0.1.4 release. It's quite terse. This format seems appropriate to me, given the high frequency of our release plus the existing source of truth for the release details on the docs site. But if you had something else in mind let me know.

@ghislaineguerin

- I don't think it makes sense for every blog post to have an image associated with it. I suggest allowing posts like this to be published without images.
- With the other test blog posts, I also notice that the images seem to require a specific aspect ratio. I suggest improving both the list of posts and the individual post layout to accommodate a wide range of aspect ratios without cropping. Wide images would be scaled down. Tall images would be scaled to a max height and then pillarboxed with empty space.
- I wasn't able to associate my new post with a "Sean Colsen" author in the same manner as the other posts were associated with other authors. I briefly tried, but gave up. I'll leave this to you to sort out. I don't think this release post necessarily needs to be associated with me. It might even be more appropriate to associate it with a generic author like "Maintainers" or something.
- The tags seem kind of weird to me, but I'm not sure to what extent this sort of content is finalized vs present only for development and testing. I would imagine each release post being tagged only with "release". Like, I'm not sure what the utility of a "mathesar" tag will be. It's hard to tell without seeing more posts, so perhaps you already have a tagging scheme in mind.
- Within the list of posts, I notice that each list item displays a truncated body of the blog post. This is great. And also I'd like to be able to configure where that truncation occurs on a per-post basis. I've done that on other platforms in the past. Do we have a mechanism for that. In particular, with the post I added, I'd like to show the full body content within the list view since it's quite short. But also I have a slight preference for formatting that content in two separate paragraphs. Is this possible?

**Comment by kgodey** [comment]
@seancolsen Your blog post is not what I was envisioning at all. We should at least include all the new features and screenshots from the release notes.

Blog posts are for marketing. For example, here's a recent [release announcement from Baserow](https://baserow.io/blog/baserow-1-22-release-notes). The post you've written has no specific information about what's contained in the release and I'm not sure what the utility of it is supposed to be. Also, I'm not sure how the release notes being the source of truth or the frequency of our releases is relevant to any of this.

**Comment by kgodey** [comment]
@seancolsen Separately, regarding your other feedback:
- I don't think it makes sense to block this PR on an RSS feed, it's something we can add later. 
- I also don't think it makes sense to block this PR on supporting more image dimensions / no images. We can add support for them as we need them. The release post should absolutely have an image.
- If the truncated post configuration is non-trivial to implement, we should also not block this work on it.

**Comment by seancolsen** [comment]
@kgodey I've pushed more changes that I hope will be more in-line with your expectations here. Can you please re-review? I've assigned you.

@ghislaineguerin for context, Kriti and I discussed this on a call yesterday. The plan we came up with is as follows:

- In general, each release will have an accompanying blog post.
- The blog post will have a screenshot of something relevant to the release.
- The blog post will link prominently to the release notes.
- We'll copy the "features" section out of the release notes, remove the PR hyperlinks, and paste it into the blog post.

I also tweaked some of the formatting ­— changing the headings to a list since that seemed nicer. I don't feel strongly about this though.

It's worth mentioning the image hosting situation is a little messy here. Within our release notes on the docs site, the images are actually hosted on GitHub. This is not ideal but was the fastest path towards completion. We have a similar thing happening here, with the exception of the marquee image which (within this PR) would be hosted on mathesar.org. I don't feel strongly about this image hosting setup, but I do have a desire to minimize grunt work in terms of moving images around if we can avoid it. If either of you have opinions on this subject, I'm curious to hear them.

Other points:

- > I don't think it makes sense to block this PR on an RSS feed, it's something we can add later.

    Kriti and I discussed this on the call and agreed we can add this later.

    @ghislaineguerin I would be curious to hear any thoughts you have on how much time you anticipate this taking. If this would be quick for you, then I would argue in favor of prioritizing it soon after merging this PR.

- > I also don't think it makes sense to block this PR on supporting more image dimensions

    My point here is that the post listing looks kind of embarrassing with the current behavior of images. 

    image

    If it were up to me, I would either publish this without an accompanying image, or I would fix the behavior of images to pillar-box tall images like this. But I'll leave it to you two to make the call. I don't feel strongly about it.

- > If the truncated post configuration is non-trivial to implement, we should also not block this work on it.

    This doesn't need to block this PR. I also noticed that if I join the first and second paragraphs of my post, the hyperlink to the release notes is stripped out when the blog system creates the post summary. That kind of makes sense, and I imagine that might actually be more difficult to change. I don't think it's too bad requiring readers to click through to the blog post to get to that link. So unless this really is trivial to change, I think we should probably just forget about this.

**Comment by ghislaineguerin** [comment]
Thanks @seancolsen 
The tags were just examples and not final. We don't need all of those tags. I do think the image behavior needs to be fixed for release. I will work on that.

**Comment by kgodey** [comment]
@seancolsen I pushed some minor changes to the blog post in https://github.com/mathesar-foundation/mathesar-website/pull/89/commits/09559b27689279cda39e9c244140b47bd62e4679, please review. I used headers instead of bullet points, I find that much easier to read, and I made the beginning and end a little more narrative.

The only thing needed from you now is to review those changes + provide a short bio for your author page. 

I don't like that the featured image shows up twice on the blog entry page, but that will be feedback for @ghislaineguerin to fix, so you don't need to worry about it.

**Comment by kgodey** [comment]
@ghislaineguerin this is looking a lot better, some more feedback.

### Homepage
Screenshot 2024-02-21 at 22-37-49 Mathesar

This looks good, this is more along the lines of what I was thinking of. Two small things if they are quick to do. If they won't be quick to do, let me know.
(1) can we put the "New on our Blog" inside the blue box somehow?
(2) Can we make it more "title like", like maybe put it in caps like the "Open Source Database Interface" below (or some other idea is fine too, just something to make the text not look like the blog text)
(3) Can we truncate the post after the first period?

### Blog entry page
Mathesar_0_1_4_Released_Mathesar

Text is looking a lot more readable, nice work. FYI, I changed the "Recent blog posts" text to sentence case instead of title case, which seemed to make more sense to me.

(1) Can we change the date format to the same date format as the homepage? If we could localize the format, that would be ideal, but I don't think we need to spend time on that right now. We should be consistent about which format we use, though, and the one on the homepage seems more standard to me.

(2) Do we need to show the featured image on top? I think the featured image should only be used in the thumbnail. e.g. in Sean's post, we're showing it on top, and then also showing it in the body.

### Main blog list, tag, author pages.

These all look good. A couple of small things:

(1) Can we make the "continue reading" links a bit more prominent? Maybe make them buttons?

(2) Can we center the subtitle on all the pages? It looks especially weird on the author and tag pages where the text is shorter.

(3) On the tag and author pages, can we change the `<title>` tag text to say "Blog - Mathesar" also? It just says the tag or author right now.

(4) Date format thing also applies here.

(5) Is there a way to reduce the space between the header and the start of the first blog post card? It looks a bit too empty.

Anyway this is coming together nicely, good work!

**Comment by kgodey** [comment]
@seancolsen I forgot to reply to your other points, I think the image hosting situation is fine for now and we can fix later if needed. If we did fix it, I'm inclined to have some sort of automation like we had in the (old) wiki repo, where you could link external images and we would replace it with a local version.

I somehow missed that you deliberately changed the headings to a list, I found that much harder to read, but you said you didn't have a strong opinion so I don't think it matters.

The tags and the other two blog posts are just placeholders so the design could be reviewed, we'll clean them up before this is merged.

**Comment by seancolsen** [comment]
> The only thing needed from you now is to review those changes + provide a short bio for your author page.

@kgodey I'm trying to fit this in between chasing screaming children — your changes look great. Review approved. For the bio, I'm not really sure how to proceed. I see the file `authors/sean_colsen.md`. Do I put a bio there? Are there other bios that exist to guide me on the intended format and length? I looked at the other files in that same directory but none of them seemed to have bio data either. Is this something we can handle later? Can you write it for me? How high of a priority is this right now? Can it just be empty?

**Comment by kgodey** [comment]
@seancolsen Just post the bio here on the PR, I'll figure out where it needs to go. It can just be a two to three line thing, first line explaining what you do at Mathesar, next 1-2 lines with some info about your background prior to Mathesar, and if you'd like to include it, your location and/or your interests.

Here is [my CC bio](https://creativecommons.org/person/kriticreativecommons-org/) for example, but it doesn't need to be this long.

**Comment by kgodey** [comment]
@ghislaineguerin One more piece of feedback I forgot to put in the last note, can we combine the data for our team on the About page and the authors? 

It's weird that Sean is listed as Engineer on the about page but Core Staff on the blog bio, we should use the same title everywhere and shouldn't have to specify in two different places. It would be nice to store the bio in the same place too.

**Comment by ghislaineguerin** [comment]
@kgodey that makes sense. I thought about it too. The reason I have the authors file is so that I can generate the author pages. I've added the titles as example but I can make them all the same. We could also just use the team data and generate all the pages even if there aren't any posts. I think that might actually be best.

**Comment by seancolsen** [comment]
@kgodey 

> Sean Colsen is an engineer on the Mathesar Maintainers team, focusing mostly on front end work. As a self-taught coder, he's been building cool stuff with web tech since 2007.

**Comment by kgodey** [comment]
@seancolsen looks great, thanks.

**Comment by ghislaineguerin** [comment]
@kgodey Everything else is done. I have updated readme with instructions and added RSS feed link in the footer.

**Review by kgodey — APPROVED** [review]

**Comment by kgodey** [comment]
@ghislaineguerin I did some small changes before merge, please take a look.

**Pull request merged**
