### PR TITLE
Add Anish to team page, update role as 'Engineer' instead of 'Frontend/Backend developer'.

### PR DESCRIPTION
**Pull request by ghislaineguerin**
This PR adds Anish to the team page and updates roles as 'Engineer' instead of 'Frontend/Backend developer'

### CODE REVIEW

**Comment by pavish** [comment]
@ghislaineguerin @kgodey I've added two commits to this PR: https://github.com/centerofci/mathesar-website/pull/97/commits/3e23b5034705510857516554d11d5b1232182904 and https://github.com/centerofci/mathesar-website/pull/97/commits/a3123c06a11ad21c56e577b0cf3efa6ef220b0ca, to update the roles as 'Engineer' instead of 'Frontend/Backend developer'.

I had a chat with Kriti on this previously, and also confirmed with both Brent and Sean.

**Comment by seancolsen** [comment]
@kgodey I'd like to move this PR along. Is there anything we're waiting on here other than your review?

**Comment by kgodey** [comment]
No, I just lost track of this, I'll add it to my queue.

**Review by kgodey — APPROVED** [review]

**Comment by kgodey** [comment]
@Anish9901 your database usage quote was a bit longer than everyone else's, so I shortened it. If it looks okay to you, please merge, otherwise update it and assign back to me for review.

**Pull request merged**
